services:
  - type: web
    name: trade-assistant-rag-chatbot
    runtime: python3
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python rag_server.py
    envVars:
      - key: PORT
        value: 10000
      - key: LLM_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: false